from ai import *
from orc import *
from troll import *
from minotaur import *
from bat import *
from imp import *
from witch import *
from ninja import *
from serpent import *
from giant import *
from spider import *
from zombie import *
from wizard import *
from priest import *
from phantasm import *